language: python

branches:
  only:
    - master

python:
  - "2.7"

before_install:
  - "easy_install pip==1.4.1"
  - pip install flake8

install:
  - pip install -e .[docs]
  - paver sync

script:
  - python manage.py test geoshape.core.tests
  - flake8 geoshape
  - cd docs && make html

after_script:
  - paver reset_hard

notifications:
  irc:
    channels:
      - "irc.freenode.org#rogue"